name: places
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3


  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  circular_check_box: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - res/assets/hotel.svg
    - res/assets/cafe.svg
    - res/assets/museum.svg
    - res/assets/park.svg
    - res/assets/restaurant.svg
    - res/assets/special_place.svg


  fonts:
    - family: Roboto
      fonts:
      - asset: res/roboto/Roboto-Regular.ttf
      - asset: res/roboto/Roboto-Black.ttf
      - asset: res/roboto/Roboto-BlackItalic.ttf
        style: italic
      - asset: res/roboto/Roboto-Bold.ttf
        weight: 700
      - asset: res/roboto/Roboto-BoldItalic.ttf
        style: italic
      




